AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: Run a simple function in the cloud with an HTTP Endpoint
Resources:
  BucketScannerV2:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ChaosChimp
      Runtime: go1.x
      Timeout: 10
      MemorySize: 128
      ReservedConcurrentExecutions: 2
      Role: arn:aws:iam::736759784672:role/service-role/testLambdaRole
      Description: A golang lambda function that randomly deletes from DOOMED_FOLDER
      Environment:
        Variables:
          DOOMED_BUCKET: golang-lambda-demo
          DOOMED_FOLDER: production.config
      Events:
        Request:
          Properties:
            Method: GET
            Path: /
          Type: Api
      CodeUri: ./dist/CC.zip
