AWSTemplateFormatVersion: 2010-09-09
Resources:
  GetRandomPerson:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetPerson:
          Type: Api
          Properties:
            Path: /
            Method: get